### ISSUE TITLE
cubicspline.cc fails to compile with eigen-3.3.6 in Debug mode on Fedora 29

### ISSUE THREAD

**Issue by junghans** [votca/tools#85]
```
[  2%] Building CXX object tools/src/libtools/CMakeFiles/votca_tools.dir/cubicspline.cc.o
In file included from /usr/include/eigen3/Eigen/Core:491,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /votca/tools/include/votca/tools/eigen.h:49,
                 from /votca/tools/include/votca/tools/spline.h:21,
                 from /votca/tools/include/votca/tools/cubicspline.h:21,
                 from /votca/tools/src/libtools/cubicspline.cc:18:
/usr/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function ‘void Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs>::operator()(const DataMapper&, const LhsScalar*, const RhsScalar*, Index, Index, Index, Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar, Index, Index, Index, Index) [with LhsScalar = double; RhsScalar = double; Index = long int; DataMapper = Eigen::internal::blas_data_mapper<double, long int, 0, 0>; int mr = 4; int nr = 4; bool ConjugateLhs = false; bool ConjugateRhs = false]’:
/usr/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1203:104: error: inconsistent operand constraints in an ‘asm’
             #define EIGEN_GEBP_2PX4_SPILLING_WORKAROUND __asm__  ("" : [a0] "+rm" (A0),[a1] "+rm" (A1));
                                                                                                        ^
```

it can be reproduced with the following dockerfile:
```Dockerfile
FROM fedora:29
RUN dnf install -y git cmake gcc-c++ expat-devel fftw-devel boost-devel txt2tags sqlite-devel hdf5-devel eigen3-devel gromacs-devel gromacs
RUN git clone --recursive https://github.com/votca/votca
WORKDIR votca/
RUN mkdir build
WORKDIR build/
RUN cmake -DCMAKE_BUILD_TYPE=Debug ..
RUN make
```

**Comment by junghans** [comment]
It is a bug in Eigen-3.3.6 http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1643, Eigen-3.3.7 should have a fix.

**Comment by junghans** [comment]
Report to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1662071

**Comment by junghans** [comment]
There is a fix in Fedora now: https://src.fedoraproject.org/rpms/eigen3/c/176ab5000f047390278680f14267d5f5936ad67c?branch=master

**Comment by JensWehner** [comment]
Thanks for finding this.

**Comment by junghans** [comment]
Fedora has an update pending: https://bodhi.fedoraproject.org/updates/FEDORA-2018-5905fb6984, I will include this in our docker container as soon as it hits testing.

**Comment by J-Dunn** [comment]
> Fedora has an update pending: https://bodhi.fedoraproject.org/updates/FEDORA-2018-5905fb6984, I will include this in our docker container as soon as it hits testing.

Pet the bug post, if you want this now user updates-testing:

$ dnf update eigen3 --enablerepo=updates-testing

**Comment by junghans** [comment]
@J-Dunn thanks we worked around the issue in votca/buildenv#20 and will finally resolve it when eigen3 is in stable with votca/buildenv#21.
